export const monkeys = [
    {
        id: 1,
        name: 'Sheerabert',
        image: 'sheerabert.png',
        size: 'small',
        category: 'blue',
        superPower: 'stops panic attacks',
        price: 20,
    },
    {
        id: 2,
        name: 'Luuva',
        image: 'luva.png',
        size: 'medium',
        category: 'purple',
        superPower: 'cleans up spills and messes',
        price: 15,
    },
    {
        id: 3,
        name: 'ArgyLynnda',
        image: 'argylynda.png',
        size: 'medium',
        category: 'argyle',
        superPower: 'dances a mean disco',
        price: 25,
    },
    {
        id: 4,
        name: 'Cloakedkent',
        image: 'argylynda.png',
        size: 'small',
        category: 'invisible',
        superPower: 'hides your fears in a distant multiverse',
        price: 120,
    },
    {
        id: 5,
        name: 'Tannerd',
        image: 'tannerd.png',
        size: 'small',
        category: 'tan',
        superPower: 'Sings soothing AMSR sounds',
        price: 20,
    },
];
