export const monkeys = [
{
    name: 'Sheerabert',
    image: 'sheerabert.png',
    size: 'small',
    category: 'blue',
    superPower: 'stops panic attacks',
    price: 20,
},
{
    name: 'Luuva',
    image: 'luva.png',
    size: 'medium',
    category: 'purple',
    superPower: 'cleans up spills and messes',
    price: 15,
},
{
    name: 'ArgyLynnda',
    image: 'argylynda.png',
    size: 'medium',
    category: 'argyle',
    superPower: 'dances a mean disco',
    price: 25,
},
{
    name: 'Cloakedkent',
    image: 'argylynda.png',
    size: 'small',
    category: 'invisible',
    superPower: 'hides your fears in a distant multiverse',
    price: 120,
},
{
    name: 'Tannerd',
    image: 'tannerd.png',
    size: 'small',
    category: 'tan',
    superPower: 'Sings soothing AMSR sounds',
    price: 20,
},
]
